### ISSUE TITLE
Add validation to JA tokens

### ISSUE THREAD

**Issue by andrew-mcgee-alloy** [Austinj0/CS-Chrome-Extension#3]
Check for 'JA-' prefix.
Check for 23-character length.

**Comment by andrew-mcgee-alloy** [comment]
I was able to submit a dodgy Eval token via the extension's UI so we probably want to double check those validations too.

**Comment by Austinj0** [comment]
I made the changes [here](https://github.com/Austinj0/CS-Chrome-Extension/pull/5)
I'll test some more before merging

**Comment by Austinj0** [comment]
Resolved, now when ja is chosen, the input will validate pattern and length are correct
