### ISSUE TITLE
Make OS lookback window consistent

### ISSUE THREAD

**Issue by andrew-mcgee-alloy** [Austinj0/CS-Chrome-Extension#4]
- Using the 'LOGS' hyperlink
    - The OpenSearch time range (+/- 1hr) is properly set, but;
    - I'm not able to see any relevant logs returned
- Using the extension's own form fields
    - The OpenSearch time range is just set to 3 months, but;
    - I'm able to see the logs

**Comment by Austinj0** [comment]
I see this happens sometimes when using the evaluation filter but not always. 
I see it on older evaluations. @andrew-mcgee-alloy can you test some scenarios as well? maybe we can pin point what the root cause is.

**Comment by andrew-mcgee-alloy** [comment]
Checked a few more cases and whenever the 'LOGS' hyperlink is unable to find any logs, I'm also unable to find any logs using my usual manual process.

Checked that there are no strange differences in the URL/query syntax across Evals using the 'LOGS' hyperlink.

I'm wondering if there's just some weird aspects to which calls are logged, depending on the Eval? Will dig some more.

**Comment by andrew-mcgee-alloy** [comment]
Confirmed that we weren't logging some evals.
